version: "3.9"

volumes:
  postgres16:

services:
  giveffektivt-db:
    build: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=giveffektivt
    ports:
      - 5432:5432
    volumes:
      - postgres16:/var/lib/postgresql/data
