version: "3.9"

volumes:
  postgres14:

services:
  giveffektivt-db:
    build: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=giveffektivt
    ports:
      - 5432:5432
    volumes:
      - postgres14:/var/lib/postgresql/data
