list:
    @just -l

donation:
    @cat Donation_Form.tsx helpers.ts helpers-donation.ts

membership:
    @cat Membership_Form.tsx helpers.ts helpers-membership.ts

newsletter:
    @cat Newsletter_Form.tsx helpers.ts helpers-newsletter.ts

fundraiser-admin:
    @cat Fundraiser_Admin.tsx helpers.ts

fundraiser:
    @cat Fundraiser.tsx helpers.ts

renew-payment:
    @cat Renew_Payment.tsx helpers.ts

stats:
    @cat Stats.tsx helpers.ts

wealth-calculator:
    @cat Wealth_Calculator.tsx helpers.ts
