name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Validate only
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Fetch dependencies
        run: yarn install
      - name: Build app
        run: yarn build

  dev:
    name: Validate + DEV
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/dev/') && github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Fetch dependencies
        run: yarn install
      - name: Build app
        run: yarn build
      - name: Deploy to DEV
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          npx vercel --token ${{ secrets.VERCEL_TOKEN }}

  prod:
    name: Validate + PROD
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Fetch dependencies
        run: yarn install
      - name: Build app
        run: yarn build
      - name: Deploy to PROD
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      - name: Redeploy DEV to have Vercel preview URL point to it
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          git checkout $(git rev-parse HEAD) # to deploy to -git-head- URL
          npx vercel --token ${{ secrets.VERCEL_TOKEN }}
